version: '3'

services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: .dockerfile
    ports:
      - "3000:3000"
      
  api:
    image: api
    environment: 
       - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/credentials.json
       - ASPNETCORE_ENVIRONMENT=Production
       - ASPNETCORE_URLS=https://+:8787;http://+:5184
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/certificate/https/certificate.pfx
       - ASPNETCORE_KESTREL__Certificates__Default__Password=aspnet
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/keys/credentials.json:ro
    build:
      dockerfile: .dockerfile
    ports:
      - "8787:8787"
      

      