name: .NET

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      -  
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with: 
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      -  
        name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      - 
        name: Add submodules
        run: git submodule init && git submodule update
      -  
       name: Restore dependencies
       run: dotnet restore
      -  
        name: Build
        run: dotnet build 
      -   
        name: Test
        run: dotnet test --no-restore
        
  push: 
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      -   
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -   
        name: Build api
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/pedagogical-load-visualizer:api
      -   
        name: Build frontend
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/pedagogical-load-visualizer:frontend
      -   
        name: Docker push
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pedagogical-load-visualizer:api
          docker push ${{ secrets.DOCKER_USERNAME }}/pedagogical-load-visualizer:frontend